#ifndef RL_DEEPLEARNING_CONTANTS_H_
#define RL_DEEPLEARNING_CONTANTS_H_

#define AZ_ENVIRONMENT_NAME "othello"
#define AZ_N_ITERATIONS 60
#define AZ_N_EPISODES 128
#define AZ_N_SIMULATIONS 800
#define AZ_LEARNING_RATE 0.00025f
#define AZ_CRITIC_COEF 0.5f
#define AZ_N_EPOCHS 4
#define AZ_N_BATCHES 8
#define AZ_N_TESTING_EPISODES 32
#define AZ_NETWORK_LOAD_NAME ""
#define AZ_NETWORK_SAVE_NAME "temp.pt"
#define AZ_N_TESTING_SUBTREE_ASYNC_STEPS 8
#define AZ_N_VISITS 1.0f
#define AZ_N_WINS -1.0f
#define AZ_CPUCT 2.5f
#define AZ_DIRICHLET_EPSILON 0.25f
#define AZ_DIRICHLET_ALPHA -1.0f
#define AZ_N_SUBTREES 128
#define AZ_N_TRAINING_SUBTREE_ASYNC_STEPS 1
#define AZ_COMPLETE_TO_END_RATIO 0.25f
#define AZ_NO_RESIGN_THRESHOLD -0.8f
#define AZ_NO_RESIGN_STEPS 30

#endif