#include "damma.hpp"
#include "othello.hpp"
#include "tictactoe.hpp"
#include "walls.hpp"
#include "santorini.hpp"
#include "english_draughts.hpp"
#include "gobblet_goblers.hpp"
#include "migoyugo.hpp"